server:
  port: 9999

management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cloud-zipkin #\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3\u7684\u540D\u5B57\uFF0C\u53EF\u4EE5\u6620\u5C04ip