server:
  port: 8762

spring:
  application:
    name: eureka-provider
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .html
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    settings:
      default_encoding: UTF-8
      output_encoding: UTF-8
      url_escaping_charset: UTF-8
      tag_syntax: auto_detect
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
  datasource:
    url : jdbc:mysql://localhost:3306/yufulian
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 2000
        default-requeue-rejected: false

#指定mybatis映射文件的地址
mybatis:
  typeAliasesPackage: com.cloud.provider.modal
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/