eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8901

spring:
  application:
    name: cloud-feign
  zipkin:
      base-url: http://localhost:9999
  sleuth:
    sampler:
      percentage: 1.0


feign:
  hystrix:
    enabled: true

