eureka:
  instance:
    appname: config-server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuHaikun/cloud-micro-service
          searchPaths: cloud-config
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh